# Generated by Django 5.2.4 on 2025-09-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpackage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
