# Generated by Django 5.2.4 on 2025-11-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_registers', '0002_alter_cashregister_id'),
        ('gyms', '0002_alter_gym_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='register_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='cashregister',
            unique_together={('gym', 'register_date')},
        ),
    ]
