# Generated by Django 5.2.8 on 2025-11-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_value'),
        ('gyms', '0002_alter_gym_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='gyms.gym'),
            preserve_default=False,
        ),
    ]
