# Generated by Django 5.2.4 on 2025-09-12 23:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_registers', '0001_initial'),
        ('payment_methods', '0001_initial'),
        ('payment_packages', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('observations', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cash_registers.cashregister')),
                ('payment_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment_packages.paymentpackage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_values', to='payments.payment')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_values', to='payment_methods.paymentmethod')),
            ],
        ),
    ]
