# Generated by Django 5.2.4 on 2025-10-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_id_alter_paymentvalue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receiver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
