# Generated by Django 5.2.4 on 2026-01-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_id_alter_studentstatus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
